apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-minikube
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo
  source:
    repoURL: https://github.com/Marshall-S-Pillai/argocd-gitops-demo.git
    targetRevision: HEAD
    path: apps/demo/overlays/minikube
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
